Update criarusuario

diff --git a/Modulos/criarusuario b/Modulos/criarusuario
--- a/Modulos/criarusuario
+++ b/Modulos/criarusuario
@@ -254,71 +254,73 @@ fun_edithost() {
     fi
 }
 
-[[ ! -e /usr/lib/vpsmanager ]] && exit 0
-tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-8s\n' "       CREAR USUARIO SSH/SSL/DROPBEAR";tput sgr0
-echo ""
-echo -ne "\033[1;32mName of User:\033[1;37m ";read username
-[[ -z $username ]] && {
-	echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
+	[[ ! -e /usr/lib/vpsmanager ]] && exit 0
+	tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-8s\n' "       CREAR USUARIO SSH/SSL/DROPBEAR";tput sgr0
+	echo ""
+	echo -ne "\033[1;32mName of User: \033[1;37m";read username
+	[[ -z $username ]] && {
+	echo -e "\n${cor1}Usuario vacio o invalido!${scor}\n"
 	exit 1
-}
-[[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
-	echo -e "\n${cor1}Este usuário já existe. tente outro nome!${scor}\n"
+	}
+	[[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
+	echo -e "\n${cor1}Este usuário ya existe. tente outro nome!${scor}\n"
 	exit 1
-}
-[[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+	}
+	[[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
 	echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
 	echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
 	exit 1
-}
-sizemin=$(echo ${#username})
-[[ $sizemin -lt 2 ]] && {
-	echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
-	echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+	}
+	sizemin=$(echo ${#username})
+	[[ $sizemin -lt 3 ]] && {
+	echo -e "\n${cor1}nombre de usuário muito curto${scor}"
+	echo -e "${cor1}use mínimo tres caracteres!${scor}\n"
 	exit 1
-}
-sizemax=$(echo ${#username})
-[[ $sizemax -gt 10 ]] && {
+	}
+	sizemax=$(echo ${#username})
+	[[ $sizemax -gt 10 ]] && {
 	echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
 	echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
 	exit 1
-}
-echo -ne "\033[1;32mPass of User:\033[1;37m ";read password
+	}
+
+echo -ne "\e[1;32mPass of User: \e[1;37m";read password
 [[ -z $password ]] && {
-	echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
-	exit 1
+echo -e "\n${cor1}Contraseña vacia o invalida!${scor}\n"
+exit 1
 }
 sizepass=$(echo ${#password})
 [[ $sizepass -lt 4 ]] && {
-	echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
-	exit 1
+echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+exit 1
 }
-echo -ne "\033[1;32mDays of Expired:\033[1;37m ";read dias
-[[ -z $dias ]] && {
+	echo -ne "\033[1;32mDays of Expired: \033[1;37m";read dias
+	[[ -z $dias ]] && {
 	echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
 	exit 1
-}
-[[ ${dias} != ?(+|-)+([0-9]) ]] && {
+	}
+	[[ ${dias} != ?(+|-)+([0-9]) ]] && {
 	echo -e "\n${cor1}Você digitou um número de dias inválido!${scor}\n"
 	exit 1
-}
-[[ $dias -lt 1 ]] && {
+	}
+	[[ $dias -lt 1 ]] && {
 	echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
 	exit 1
-}
-echo -ne "\033[1;32mLimit of Connect:\033[1;37m ";read sshlimiter
+	}
+echo -ne "\033[1;32mLimit of Connect: \033[1;37m";read sshlimiter
 [[ -z $sshlimiter ]] && {
-	echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
-	exit 1
+echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
+exit 1
 }
 [[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
-	echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
-	exit 1
+echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
+exit 1
 }
 [[ $sshlimiter -lt 1 ]] && {
-	echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
-	exit 1
+echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
+exit 1
 }
+
 final=$(date "+%Y-%m-%d" -d "+$dias days")
 gui=$(date "+%d/%m/%Y" -d "+$dias days")
 pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
